spring:
  cloud:
    stream:
      binders:
#        binder 的名称，需要自己定义
        testbinder:
#          binder 的类型
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-box: /
#      默认的 binder
      default-binder: testbinder
      bindings:
        input:
          destination: scstreamExchange
          group: stream
#          绑定 binder 也可以不指定
          binder: testbinder
#          消息的类型
          contentType: text/plain
          consumer:
#            重试次数
            maxAttempts: 3
        output:
          destination: scstreamExchange
#          绑定 binder 也可以不指定
          binder: testbinder

