spring:
  cloud:
    stream:
      binders:
#        binder 的名称，需要自己定义
        testbinder:
#          binder 的类型
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-box: /
#      默认的 binder
      default-binder: testbinder
      bindings:
        output:
          destination: scstreamExchange
#          绑定 binder 也可以不指定
          binder: testbinder
          producer:
#            生产者实例 有2个
            partitionCount: 2
#            生产者索引
            partitionKeyExpression: 1
        input:
          destination: scstreamExchange
          group: stream
#          绑定 binder 也可以不指定
          binder: testbinder
          consumer:
#            打开分区消费的策略
            partitioned: true
#            消费者实例数量，2个
            instanceCount: 2
#            消费者索引，必须与生产者的索引相对应才可以
            instanceIndex: 1



